{"name": "登录密码错误", "status": "passed", "description": " 登录密码错误 ", "attachments": [{"name": "返回的结果", "source": "cec5ccfb-e569-42d4-ab63-d3d7c7e78dd9-attachment.attach"}], "start": 1599817312297, "stop": 1599817312432, "uuid": "0b5a90bb-b79d-44ab-8e25-5b1e1d4564c7", "historyId": "380f6c55ae24860eef3ad2c81e8c1c10", "testCaseId": "3ff5b394eb5c25c58d14ab4a731beaac", "fullName": "TestCase.test_login.TestLogin#test_password_error_login_02", "labels": [{"name": "feature", "value": "登录功能"}, {"name": "story", "value": "登录用例"}, {"name": "severity", "value": "blocker"}, {"name": "parentSuite", "value": "TestCase"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "WPYW29MHFFSYDPN"}, {"name": "thread", "value": "8432-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCase.test_login"}]}